### PR TITLE
Code of Kadane's Algorithm in C++

### PR DESCRIPTION
**Pull request by kartikeyaGUPTA45**
@Nikzy7  I add the code of Kadane Algorithm in C++ language
Please check and merge it.

**Kadane's Algorithm is used to find out the maximum subarray sum from an array of integers.**

Algorithm:

Begin
Function kadanes(int array[], int length):
   Initialize
   highestMax = 0
   currentElementMax = 0
   for i = 0 to length-1
      currentElementMax = max(array[i],currentElementMax + array[i])
      highestMax = max(highestMax, currentElementMax)
   return highestMax
End

### CODE REVIEW

**Review by Nikzy7 — CHANGES_REQUESTED** [review]
Hey ! I need you to add your name in contributors.md too 😄

**Comment by kartikeyaGUPTA45** [comment]
KARTIKEYA GUPTA

**Comment by Nikzy7** [comment]
NP, I'll do it myself !

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7, I added my name to contributors.md

**Pull request merged**
