### PR TITLE
C programming

### PR DESCRIPTION
**Pull request by Alisha-Ahmed**
Bubble Sort, Linear Search and Binary Search Algorithm's in C program.

### CODE REVIEW

**Comment by Alisha-Ahmed** [comment]
Hey, I did this for the first time so am a bit confused and wanted to know
if my pr was accepted and is it the right one for hactoberfest.

Please help me out for this clarification. 🙂

**Comment by Nikzy7** [comment]
Yes ! It has been merged !

**Comment by Alisha-Ahmed** [comment]
Thank you, So will it be considered as 1 out of 4 PR for hacktoberfest.?

**Comment by Alisha-Ahmed** [comment]
Thank you

**Pull request merged**
